version: '3.7'

services:

  sample-prod:
    container_name: sample-prod
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile.prod
    env_file:
      - .env.local
    ports:
      - '1337:80'
