version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - .env.local
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
